const express = require('express');
const authenticate = require('../middleware/authenticate');
const checkCompanyAccess = require('../middleware/companyAccess');
const validateRequest = require('../middleware/validateRequest');
const { createInvoiceSchema, updateInvoiceSchema, invoiceQuerySchema, validateQuery } = require('../validators/invoice.validators');
const controller = require('../controllers/invoice.controller');
const router = express.Router();
router.post('/', authenticate, validateRequest(createInvoiceSchema), checkCompanyAccess, controller.create);
router.get('/', authenticate, validateQuery(invoiceQuerySchema), checkCompanyAccess, controller.list);
router.get('/:id/pdf', authenticate, checkCompanyAccess, controller.pdf);
router.get('/:id', authenticate, checkCompanyAccess, controller.get);
router.put('/:id', authenticate, validateRequest(updateInvoiceSchema), checkCompanyAccess, controller.update);
router.delete('/:id', authenticate, checkCompanyAccess, controller.cancel);
module.exports = router;
